### ISSUE TITLE
March 12th shows up twice if you narrow the search from 2017-03-10 to 2017-03-15

### ISSUE THREAD

**Issue by thaorell** [cga-harvard/bop-ui#18]

**Comment by blewis** [comment]
Is this related to the gap that is always showing on the historgram?

**Comment by lordofhogwarts** [comment]
Yes it is that one
![screenshot 2017-06-02 11 41 24](https://cloud.githubusercontent.com/assets/25762021/26733367/9e3e6b5e-4788-11e7-8a25-b0f061f48674.png)

**Comment by Lenninlasd** [comment]
With the changes of https://github.com/cga-harvard/bop-ui/issues/6 this issue was fixed

![image](https://user-images.githubusercontent.com/7197750/27395431-c8bb0c80-567d-11e7-8671-d4b38fc4a590.png)
