### ISSUE TITLE
Incorrect gap in Tweet Histogram

### ISSUE THREAD

**Issue by dkakkar** [cga-harvard/bop-ui#6]
The tweet histogram shows an incorrect gap in March 2017, there is no gap in harvesting and data is available for all days in March 2017.

**Comment by Lenninlasd** [comment]
Can you show us a example, images or an url to replicate the issue?

**Comment by dkakkar** [comment]
![picture1](https://cloud.githubusercontent.com/assets/11283176/25144768/fde46794-243c-11e7-9670-6f628d6da5bf.png)

**Comment by Lenninlasd** [comment]
I can not see that gap in the histogram, did you do any specific search?

<img width="738" alt="screen shot 2017-04-18 at 15 12 26" src="https://cloud.githubusercontent.com/assets/7197750/25184594/885389d4-24e0-11e7-9092-2ad2419b4662.png">

**Comment by dkakkar** [comment]
No I did not do any specific search. I see the gap shown in picture above when I open http://bop.worldmap.harvard.edu/bop/#!/search

**Comment by Lenninlasd** [comment]
Fixed

**Comment by Lenninlasd** [comment]
The changes should be upload to http://bop.worldmap.harvard.edu/bop-dev/
