### ISSUE TITLE
Download Button not supported on Windows Firefox, Windows IE and Ubuntu Firefox 

### ISSUE THREAD

**Issue by thaorell** [cga-harvard/bop-ui#8]
Export does not work on Ubuntu Firefox

**Comment by blewis** [comment]
Also not working on Windows Firefox (v 53.03) and Windows IE. (v 11.0.42)

**Comment by Lenninlasd** [comment]
@lordofhogwarts @dkakkar  now you can deploy the development version and check in all the affected platforms
